server:
  port: ${PORT:8080}

spring:
  application:
    name: gatesync-app
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb+srv://thakorarpitsinh:Gatesync@cluster0.xudh85e.mongodb.net/gatesync?retryWrites=true&w=majority}
  datasource:
    url: jdbc:h2:mem:gatesync;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

gatesync:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000

logging:
  level:
    com.gatesync: DEBUG
